version: "3.7"

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: snakiepass1
      POSTGRES_USER: snakie
      POSTGRES_DB: snakie_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./test_data:/test_data
    ports:
      - "127.0.0.1:5432:5432"

  snakie-bot:
    build:
      context: .
    image: snakie-django:latest
    environment:
      DJANGO_SECRET_KEY: "arfdgvds"
      DJ_DEBUG: "False"
      BOT_TOKEN: "6118641667:AAEN1acrLYpcbYIiJ6vM7Vb_UBhM4PjYc1I"
      YOO_TOKEN: "live_WwEAUTuttMECDAn9nx-MBAyAT0jv7GsLQkqkS9vUnp4"
      SHOP_ID: "215494"
      DJ_DB_URL: 'postgres://snakie:snakiepass1@postgres:5432/snakie_db'
    depends_on:
      - postgres
    command:
      - sh
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py loaddata db_dump.json
        python manage.py async_bot

  snakie-admin:
    build:
      context: .
    image: snakie-django:latest
    ports:
      - 8000
    volumes:
      - ./nginx-templates:/app/nginx-templates
      - nginx_assets:/app/assets/
      - nginx_media:/var/www/media/
    environment:
      DJANGO_SECRET_KEY: "arfdgvds"
      DJ_DEBUG: "True"
      DJ_ALLOWED_HOSTS: '127.0.0.1,localhost,snakiesub.ru'
      DJ_CSRF_TRUSTED_ORIGINS: 'http://127.0.0.1:8000,https://snakiesub.ru'
      MEDIA_ROOT: '/var/www/media'
      BOT_TOKEN: "6118641667:AAEN1acrLYpcbYIiJ6vM7Vb_UBhM4PjYc1I"
      YOO_TOKEN: "live_WwEAUTuttMECDAn9nx-MBAyAT0jv7GsLQkqkS9vUnp4"
      SHOP_ID: "215494"
      DJ_DB_URL: 'postgres://snakie:snakiepass1@postgres:5432/snakie_db'
    depends_on:
      - postgres
      - snakie-bot
    command:
      - sh
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py runserver 0.0.0.0:8000 --noreload

  nginx:
    image: nginx
    ports:
      - '8000:80'
    environment:
      UPSTREAM_SERVER: snakie-admin:8000
    volumes:
      - ./nginx-templates:/etc/nginx/templates/
      - nginx_assets:/var/www/static/
      - nginx_media:/var/www/media/
    depends_on:
      - snakie-admin



volumes:
  db_data:
  nginx_media:
  nginx_assets:
