# Generated by Django 4.2.6 on 2023-10-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_name', models.CharField(max_length=128, verbose_name='Отображаемое имя')),
                ('payment_name', models.CharField(max_length=128, verbose_name='Отображаемый срок подписки')),
                ('amount', models.FloatField(default=0, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd'), ('EUR', 'Eur')], default='RUB', max_length=128, verbose_name='Валюта')),
                ('sub_period', models.IntegerField(default=1, verbose_name='Срок подписки')),
                ('sub_period_type', models.CharField(choices=[('by month', 'Month'), ('by day', 'Day')], default='by month', max_length=128, verbose_name='Тип периода срока подписки')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Пробная?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
