# Generated by Django 4.2.6 on 2023-10-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_period_type',
            field=models.CharField(choices=[('month', 'Month'), ('day', 'Day')], default='month', max_length=128, verbose_name='Тип периода срока подписки'),
        ),
    ]
