# Generated by Django 4.2.6 on 2023-10-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('unsub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('is_auto_renew', models.BooleanField(default=True, verbose_name='Автоматически продлевать?')),
                ('verified_payment_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Подтвержденный ID платежа (автоплатежи)')),
                ('payment_amount', models.FloatField(verbose_name='Цена подписки')),
                ('payment_currency', models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd'), ('EUR', 'Eur')], default='RUB', max_length=128, verbose_name='Валюта платежа')),
                ('payment_system', models.CharField(default='YooKassa', max_length=128, verbose_name='Платежная система')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='product.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='user.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
