# Generated by Django 4.2.6 on 2023-10-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unnamed Bot', max_length=128, null=True, verbose_name='Имя бота')),
                ('api_token', models.CharField(max_length=128, verbose_name='Ключ API')),
                ('chat_id', models.BigIntegerField(verbose_name='Чат id бота в tg')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedChat',
            fields=[
                ('name', models.CharField(blank=True, default='Unnamed chat', max_length=128, null=True, verbose_name='Название чата')),
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Чат ID в tg')),
            ],
        ),
    ]
