# Generated by Django 4.2.6 on 2023-10-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownedbot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AlterModelOptions(
            name='ownedchat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
