# Generated by Django 4.2.6 on 2023-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_parts', '0002_alter_ownedbot_options_alter_ownedchat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterPaymentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unnamed chat', max_length=128, null=True, verbose_name='Отображаемое имя ссылки')),
                ('link', models.CharField(blank=True, default='https://google.com/', max_length=128, null=True, verbose_name='Ссылка на контент')),
            ],
            options={
                'verbose_name': 'Оплачиваемый контент',
                'verbose_name_plural': 'Оплачиваемый контент',
            },
        ),
    ]
